name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, there! Thank you for taking the time to suggest a rectification to the project. You shall be replied to by the maintainer(s) soon."
        pr-message: "Hello, there! Thank you for taking the time to make changes to the project and make it better. You shall be replied to by the maintainer(s) soon."
